version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: ./spectral
      - store_test_results:
          path: ./junit-out/
